Updates setup scripts' variables to reflect settings

diff --git a/files/ssl_setup b/files/ssl_setup
--- a/files/ssl_setup
+++ b/files/ssl_setup
@@ -3,12 +3,14 @@
 # Create the SSL certificate, then finish setup
 #
 open_ssl_conf='/usr/lib/ssl/dreambox-openssl.cnf'
+IFS=',' read -r -a HOST_LIST <<< "${hosts}"
+HOST="${HOST_LIST[0]}"
 
 # Check for a saved certificate and key
-if [[ -r "/vagrant/certs/${HOST_LIST[0]}.key" && -r "/vagrant/certs/${HOST_LIST[0]}.crt" ]]; then
+if [[ -r "/vagrant/certs/${HOST}.key" && -r "/vagrant/certs/${HOST}.crt" ]]; then
   # Use the saved certs
   echo "Using saved certs from /vagrant/certs/"
-  cp -f /vagrant/certs/"${HOST_LIST[0]}".* /usr/local/apache2/conf/
+  cp -f /vagrant/certs/"${HOST}".* /usr/local/apache2/conf/
 else
   # Build the hosts strings
   for (( i=1; i<=${#HOST_LIST[@]}; i++ )); do
@@ -21,14 +23,19 @@ else
     -days 365 \
     -newkey rsa:2048 \
     -extensions v3_req \
-    -subj "/C=US/ST=Washington/L=Seattle/O=IT/CN=${host}/" \
-    -keyout "/usr/local/apache2/conf/${host}.key" \
-    -out "/usr/local/apache2/conf/${host}.crt" \
+    -subj "/C=US/ST=Washington/L=Seattle/O=IT/CN=${HOST}/" \
+    -keyout "/usr/local/apache2/conf/${HOST}.key" \
+    -out "/usr/local/apache2/conf/${HOST}.crt" \
     -config "${open_ssl_conf}";
 
   # Create the certs directory
   [[ ! -d /vagrant/certs ]] && mkdir /vagrant/certs
   # Save these for next time
-  cp -f /usr/local/apache2/conf/"${host}".* /vagrant/certs
-  [[ $? ]] && echo "SSL certificate done."
+  cp -f /usr/local/apache2/conf/"${HOST}".* /vagrant/certs
+fi
+
+if [[ $? -lt 1 ]]; then
+  echo -e "SSL certificate done.\n"
+else
+  echo -e "SSL setup error..."
 fi
